name: Dr Laura James
favicon: null
layout_spectrum: 0.5223460386041552
typography_spectrum: 0.7305052408482879
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5587510126642883
  lightness: 0.1755106239579618
  saturation: 0.18774863053113222
  rhythmicContrast: 0.6976210840512067
purpose: []
